# Generated by Django 3.2.18 on 2023-03-13 07:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=models.SET('Product deleted'), related_name='card_items', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(choices=[(1, 'New'), (2, 'Process'), (3, 'Delivered'), (4, 'Canceled')], default=1)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('phone', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '998 [XX] [XXX XX XX]'. Up to 12 digits allowed.", regex='^998[378]{2}|9[01345789]\\d{7}$')])),
                ('promo_code', models.CharField(max_length=250, null=True)),
                ('delivery_time', models.CharField(max_length=255)),
                ('latitude', models.CharField(max_length=30, null=True)),
                ('longitude', models.CharField(max_length=30, null=True)),
                ('address_name', models.CharField(max_length=222, null=True)),
                ('house', models.CharField(max_length=23, null=True)),
                ('flat', models.CharField(max_length=23, null=True)),
                ('floor', models.CharField(max_length=23, null=True)),
                ('comment', models.CharField(max_length=333, null=True)),
                ('card_items', models.ManyToManyField(to='order.CardItem')),
                ('user', models.ForeignKey(on_delete=models.SET('User deleted'), related_name='order', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
